name: PHP CodeSniffer

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read

jobs:
  phpcs:
    name: PHP CodeSniffer
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: json, dom, curl, libxml, mbstring
        coverage: none

    - name: Install dependencies
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Run PHP CodeSniffer
      run: ./vendor/bin/phpcs src
